title: Запусти велику мовну модель на Raspberry Pi
hero_image: images/banner.png
description: Встанови велику мовну модель (ВММ) з відкритим кодом Ollama на свій комп’ютер Raspberry Pi
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Що ти зробиш
  - 
    title: Встанови ВММ
    completion:
      - engaged
  - 
    title: Запусти модель
  - 
    title: Використовуй WebUI
  - 
    title: Розпізнавання зображень з WebUI
    completion:
      - internal
  - 
    title: Що ти тепер вмієш?
    completion:
      - external
