title: Run a Large Language Model on your Raspberry Pi
hero_image: images/banner.png
description: Install the open source Ollama LLM on your Raspberry Pi
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: What you will make
  - title: Install the LLM
    completion:
    - engaged
  - title: Run a model
  - title: Using the WebUI
  - title: Image recognition with WebUI
    completion:
    - internal
  - title: What can you do now?
    completion:
    - external
