title: Execute um grande modelo de linguagem no seu Raspberry Pi
hero_image: images/banner.png
description: Instale o grande modelo de linguagem (LLM) de código aberto Ollama em seu computador Raspberry Pi.
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Você vai fazer
  - 
    title: Instale o LLM
    completion:
      - engaged
  - 
    title: Execute um modelo
  - 
    title: Use a WebUI
  - 
    title: Reconhecimento de imagem com WebUI
    completion:
      - external
