title: Run a large language model on your Raspberry Pi
hero_image: images/banner.png
description: Install the open-source Ollama large language model (LLM) on your Raspberry Pi computer
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Você vai fazer
  - 
    title: Install the LLM
    completion:
      - engaged
  - 
    title: Run a model
  - 
    title: Use the WebUI
  - 
    title: Image recognition with WebUI
    completion:
      - internal
      - external
  - 
    title: Perguntas rápidas
    completion:
